from typing import Any

from django.http import HttpRequest, HttpResponseRedirect

def normalize_origin(origin: str, setting_name: str) -> str: ...
def get_configured_public_origin() -> str | None: ...
def get_allowed_origins() -> set[str]: ...
def get_request_origin(request: HttpRequest) -> str | None: ...
def get_expected_issuer() -> str | None: ...
def verify_access_token(token: str, request: HttpRequest) -> dict[str, Any] | None: ...
def is_authenticated(request: HttpRequest) -> tuple[bool, dict[str, Any]]: ...
def redirect_to_login(
    request: HttpRequest,
    scope: str | None = None,
) -> HttpResponseRedirect: ...
