from typing import Literal, TypedDict

from django.http import HttpRequest, HttpResponse

class MagicSsoCookieOptions(TypedDict):
    domain: str | None
    httponly: bool
    max_age: int | None
    path: str
    samesite: Literal['Lax', 'Strict', 'None']
    secure: bool

def get_magic_sso_cookie_samesite() -> Literal['Lax', 'Strict', 'None']: ...
def get_magic_sso_cookie_options() -> MagicSsoCookieOptions: ...
def get_default_return_url(request: HttpRequest) -> str: ...
def normalise_return_url(request: HttpRequest, return_url: str | None) -> str: ...
def build_verify_url(request: HttpRequest, return_url: str) -> str: ...
def normalise_scope(scope: str | None) -> str | None: ...
def login(request: HttpRequest) -> HttpResponse: ...
def logout(request: HttpRequest) -> HttpResponse: ...
def verify_token(request: HttpRequest) -> HttpResponse: ...
