# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Wojciech Polak

"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path


def load_env_file(path: Path) -> None:
    if not path.is_file():
        return

    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if line == '' or line.startswith('#'):
            continue

        key, separator, value = line.partition('=')
        if separator == '':
            continue

        name = key.strip()
        if name == '':
            continue

        normalised_value = value.strip()
        if (
            len(normalised_value) >= 2
            and normalised_value[0] == normalised_value[-1]
            and normalised_value[0] in {"'", '"'}
        ):
            normalised_value = normalised_value[1:-1]

        os.environ.setdefault(name, normalised_value)


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default

    normalised = value.strip().lower()
    if normalised in {'1', 'true', 'yes', 'on'}:
        return True
    if normalised in {'0', 'false', 'no', 'off'}:
        return False

    raise ValueError(f'Invalid boolean value for {name}: {value}')


def env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None or value.strip() == '':
        return default

    return int(value)


def env_list(name: str, default: list[str]) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return default

    values = [item.strip() for item in value.split(',') if item.strip()]
    return values or default


def env_choice(name: str, default: str, choices: set[str]) -> str:
    value = os.getenv(name)
    if value is None:
        return default

    normalised = value.strip()
    if normalised in choices:
        return normalised

    choices_text = ', '.join(sorted(choices))
    raise ValueError(f'Invalid value for {name}: {value}. Expected one of: {choices_text}')


def env_text(name: str, default: str) -> str:
    value = os.getenv(name)
    if value is None:
        return default

    normalised = value.strip()
    return normalised or default


def env_cookie_path(name: str, default: str) -> str:
    value = os.getenv(name)
    if value is None or value.strip() == '':
        return default

    normalised = value.strip()
    if not normalised.startswith('/'):
        raise ValueError(f'{name} must start with "/": {value}')

    return normalised


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_env_file(Path(os.getenv('MAGICSSO_DOTENV_PATH', BASE_DIR / '.env')))
DEVELOPMENT_SECRET_KEY = 'django-insecure-local-demo-only-not-for-production'


def ensure_safe_deployment_settings(
    debug: bool,
    secret_key: str,
    allowed_hosts: list[str],
) -> None:
    if debug:
        return

    if secret_key == DEVELOPMENT_SECRET_KEY:
        raise ValueError(
            'DJANGO_SECRET_KEY must be set to a unique value when DJANGO_DEBUG is false.'
        )

    if not allowed_hosts:
        raise ValueError(
            'DJANGO_ALLOWED_HOSTS must list at least one host when DJANGO_DEBUG is false.'
        )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: this fallback secret is for the localhost demo only.
SECRET_KEY = env_text('DJANGO_SECRET_KEY', DEVELOPMENT_SECRET_KEY)

# SECURITY WARNING: keep DJANGO_DEBUG enabled only for local development.
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1'] if DEBUG else [],
)
ensure_safe_deployment_settings(DEBUG, SECRET_KEY, ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'hello',
    'magic_sso_django',
]

# This demo intentionally skips Django's built-in auth/session apps because
# Magic Link SSO middleware owns access checks in the example.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'magic_sso_django.middleware.MagicSsoMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'hello/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#
# Magic Link SSO settings
#

MAGICSSO_AUTH_EVERYWHERE = env_bool('MAGICSSO_AUTH_EVERYWHERE', False)
MAGICSSO_COOKIE_DOMAIN = os.getenv('MAGICSSO_COOKIE_DOMAIN') or None
MAGICSSO_COOKIE_MAX_AGE = env_int('MAGICSSO_COOKIE_MAX_AGE', 0) or None
MAGICSSO_COOKIE_NAME = os.getenv('MAGICSSO_COOKIE_NAME', 'magic-sso')
MAGICSSO_COOKIE_PATH = env_cookie_path('MAGICSSO_COOKIE_PATH', '/')
MAGICSSO_COOKIE_SAMESITE = env_choice('MAGICSSO_COOKIE_SAMESITE', 'Lax', {'Lax', 'Strict', 'None'})
MAGICSSO_COOKIE_SECURE = env_bool('MAGICSSO_COOKIE_SECURE', not DEBUG)
MAGICSSO_DIRECT_USE = env_bool('MAGICSSO_DIRECT_USE', True)
MAGICSSO_JWT_SECRET = os.getenv(
    'MAGICSSO_JWT_SECRET',
    'VERY-VERY-LONG-RANDOM-JWT-SECRET',
)
MAGICSSO_PREVIEW_SECRET = os.getenv(
    'MAGICSSO_PREVIEW_SECRET',
    'VERY-VERY-LONG-RANDOM-PREVIEW-SECRET',
)
MAGICSSO_PUBLIC_URLS = env_list('MAGICSSO_PUBLIC_URLS', ['login'])
MAGICSSO_REQUEST_TIMEOUT = env_int('MAGICSSO_REQUEST_TIMEOUT', 5)
MAGICSSO_SERVER_URL = os.getenv('MAGICSSO_SERVER_URL', 'http://localhost:3000')
